package com.exchange.matching.server.repository;
import com.exchange.matching.server.dto.EngineConfiguration;
import com.exchange.matching.server.dto.DashboardPreferences;
import com.exchange.matching.server.service.PasswordHash;
import tools.jackson.databind.json.JsonMapper;
import java.io.IOException;
import java.nio.file.*;
import java.sql.*;
import java.util.*;

/** File-backed H2; credentials and ordered configuration history commit before application. */
public final class AdminStore implements ConfigurationStore {
    private final Connection connection;
    private final JsonMapper mapper = JsonMapper.builder().build();
    public AdminStore(Path directory) throws IOException {
        try {
            Files.createDirectories(directory);
            connection = DriverManager.getConnection("jdbc:h2:file:" + directory.toAbsolutePath().normalize().resolve("matching-admin").toString().replace('\\','/') + ";DB_CLOSE_ON_EXIT=FALSE;WRITE_DELAY=0", "sa", "");
            try (var statement = connection.createStatement()) {
                statement.execute("CREATE TABLE IF NOT EXISTS admin_user (username VARCHAR(64) PRIMARY KEY, password_hash VARCHAR(256) NOT NULL, version BIGINT NOT NULL)");
                statement.execute("CREATE TABLE IF NOT EXISTS dashboard_preferences (username VARCHAR(64) PRIMARY KEY REFERENCES admin_user(username), theme VARCHAR(16) NOT NULL, language VARCHAR(16) NOT NULL)");
                statement.execute("CREATE TABLE IF NOT EXISTS engine_configuration (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, payload CLOB NOT NULL)");
            }
            try (var query = connection.prepareStatement("SELECT username FROM admin_user WHERE username='root'"); var rows = query.executeQuery()) {
                if (!rows.next()) try (var insert = connection.prepareStatement("INSERT INTO admin_user VALUES ('root', ?, 1)")) {
                    insert.setString(1, PasswordHash.encode("root")); insert.executeUpdate();
                }
            }
        } catch (SQLException e) { throw new IOException("Cannot open admin database", e); }
    }
    public synchronized DashboardPreferences dashboardPreferences() {
        try (var query = connection.createStatement(); var rows = query.executeQuery("SELECT theme, language FROM dashboard_preferences WHERE username='root'")) {
            return rows.next() ? new DashboardPreferences(rows.getString(1), rows.getString(2)) : new DashboardPreferences("dark", "zh-CN");
        } catch (SQLException e) { throw new IllegalStateException("Preferences storage unavailable", e); }
    }
    public synchronized void saveDashboardPreferences(DashboardPreferences preferences) {
        preferences.validate();
        try (var update = connection.prepareStatement("MERGE INTO dashboard_preferences (username, theme, language) KEY(username) VALUES ('root', ?, ?)")) {
            update.setString(1, preferences.theme()); update.setString(2, preferences.language()); update.executeUpdate();
        } catch (SQLException e) { throw new IllegalStateException("Preferences storage unavailable", e); }
    }
    public synchronized long version() {
        try (var query = connection.createStatement(); var rows = query.executeQuery("SELECT version FROM admin_user WHERE username='root'")) { rows.next(); return rows.getLong(1); }
        catch (SQLException e) { throw new IllegalStateException("Account storage unavailable", e); }
    }
    public synchronized boolean authenticate(String username, String password) {
        try (var query = connection.createStatement(); var rows = query.executeQuery("SELECT password_hash FROM admin_user WHERE username='root'")) {
            rows.next(); boolean valid = PasswordHash.matches(password, rows.getString(1)); return "root".equals(username) && valid;
        } catch (SQLException e) { throw new IllegalStateException("Account storage unavailable", e); }
    }
    public synchronized boolean changePassword(String oldPassword, String newPassword) {
        if (newPassword == null || newPassword.length() < 8 || newPassword.length() > 128) throw new IllegalArgumentException("新密码长度须为 8–128 个字符");
        if (!authenticate("root", oldPassword)) return false;
        try (var update = connection.prepareStatement("UPDATE admin_user SET password_hash=?, version=version+1 WHERE username='root'")) {
            update.setString(1, PasswordHash.encode(newPassword)); update.executeUpdate(); return true;
        } catch (SQLException e) { throw new IllegalStateException("Account storage unavailable", e); }
    }
    public synchronized List<EngineConfiguration> readAll() throws IOException {
        try (var query = connection.createStatement(); var rows = query.executeQuery("SELECT payload FROM engine_configuration ORDER BY id")) {
            var result = new ArrayList<EngineConfiguration>();
            while(rows.next()) result.add(mapper.readValue(rows.getString(1), EngineConfiguration.class));
            return result;
        } catch (SQLException e) { throw new IOException(e); }
    }
    public synchronized void append(EngineConfiguration configuration) throws IOException {
        try (var insert = connection.prepareStatement("INSERT INTO engine_configuration(payload) VALUES (?)")) {
            insert.setString(1, mapper.writeValueAsString(configuration)); insert.executeUpdate();
        } catch (SQLException e) { throw new IOException(e); }
    }
    public synchronized void migrate(List<EngineConfiguration> configurations) throws IOException {
        if (!readAll().isEmpty() || configurations.isEmpty()) return;
        try {
            connection.setAutoCommit(false);
            for (var item : configurations) append(item);
            connection.commit();
        } catch (SQLException | IOException | RuntimeException e) {
            try { connection.rollback(); } catch (SQLException rollback) { e.addSuppressed(rollback); }
            throw new IOException("Configuration migration failed", e);
        } finally { try { connection.setAutoCommit(true); } catch (SQLException e) { throw new IOException(e); } }
    }
    @Override public synchronized void close() throws IOException { try { connection.close(); } catch (SQLException e) { throw new IOException(e); } }
}
